# SETUP
baseurl = "/"
DefaultContentLanguage = "en"
publishdir = "public"
canonifyUrls = "true"
disableKinds = ["RSS","taxonomy","taxonomyTerm"] # disable hugo's content that we don't need...

title = "RivertalesNL - Carp Fishing" # page title -> see ./layouts/partials/head.html

googleAnalytics = "" # if needed...

[author]
    name = "RivertalesNL"
    email = "bdcarpfishing@gmail.com"

[params]
    description = "RivertalesNL - Carp Fishing" # page description -> see ./layouts/partials/head.html
    images = [] #add images here as "img/name.ext" (points to s./static/img/) to populate the default og and twitter <meta> attributes -> see ./layouts/partials/head.html

# these items will be rendered 1. into a tooltip in the navbar and 2. into the footer - consider that there's limited space when adding more items -> see ./layouts/partials
[[params.social]]
    title = "TikTok"
    url = "https://www.tiktok.com/@rivertalesnl" # add your twitter handle
[[params.social]]
    title = "Youtube"
    url = "https://youtube.com/rivertalesnl" # add your linkedin profile URL
